name: wior
channels:
- conda-forge
- jdblischak
- nodefaults
dependencies:
- imagemagick
- phantomjs
- r-base=4.1
- r-crul>=1.2
- r-devtools
- r-gh
- r-ghapps
- r-jose
- r-rcrossref>=1.2
- r-remotes
- jdblischak::r-tinier
- r-usethis
- r-webshot
# for webshot2
- r-asioheaders
- r-websocket
